name: tttlm_env
channels:
  - conda-forge
  - defaults
  - nvidia
dependencies:
  - python=3.9
  - numpy
  - transformers
  - matplotlib
  - tqdm
  - scikit-learn
  - pip
  - pip:
    - torch
    - faiss-gpu-cu12
    - sqlitedict
    - sacrebleu
    - pycountry
    - rouge-score

